# Control parameters
CONTROL_CONN = 0
CONTROL_INSTR = 1
CONTROL_RESPONSE = 2

# Connection parameters
CONN_SYN = 0
CONN_ACK = 1
CONN_LEAVE = 2

# Instruction parameters
LIST_FILES = 0
CREATE_FILE = 1
APPEND_FILE = 2
REMOVE_FILE = 3
MOVE_FILE = 4
DOWNLOAD_FILE = 5
UPLOAD_FILE = 6

